# Generated by Django 5.0.3 on 2024-04-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maktab", "0002_user_age_user_place_of_living"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_admin",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_pupil",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_teacher",
        ),
        migrations.AddField(
            model_name="user",
            name="type",
            field=models.CharField(
                choices=[
                    ("is_admin", "is_admin"),
                    ("is_teacher", "is_teacher"),
                    ("is_pupil", "is_pupil"),
                ],
                default=1,
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
