# Generated by Django 5.0.4 on 2024-04-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maktab", "0002_remove_user_image_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                default="users_image/account.png", unique="users_image", upload_to=""
            ),
        ),
    ]
