# Generated by Django 5.0.3 on 2024-04-13 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maktab", "0003_remove_user_is_admin_remove_user_is_pupil_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="type",
        ),
        migrations.AddField(
            model_name="user",
            name="is_admin",
            field=models.BooleanField(default=False, verbose_name="Is admin"),
        ),
        migrations.AddField(
            model_name="user",
            name="is_pupil",
            field=models.BooleanField(default=False, verbose_name="Is Pupil"),
        ),
        migrations.AddField(
            model_name="user",
            name="is_teacher",
            field=models.BooleanField(default=False, verbose_name="Is Teacher"),
        ),
    ]
