# Generated by Django 5.0.3 on 2024-04-16 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maktab", "0004_remove_user_type_user_is_admin_user_is_pupil_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=55)),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="maktab.account",
            ),
        ),
    ]
