# Generated by Django 5.0.4 on 2024-04-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maktab", "0004_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(unique="users_image", upload_to=""),
        ),
    ]
