# Generated by Django 5.0.4 on 2024-04-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maktab", "0005_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(upload_to="users_image/"),
        ),
    ]
