# Generated by Django 5.0.4 on 2024-04-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maktab", "0006_alter_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(default=1, upload_to="users_image/"),
            preserve_default=False,
        ),
    ]
