# Generated by Django 5.0.4 on 2024-04-24 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("maktab", "0007_user_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
